[tool.tartufo]
repo-path = "."
regex = true
entropy = true
exclude-path-patterns = [
 {path-pattern = 'tartufo\.toml', reason = 'tartufo file'},
 {path-pattern = 'package-lock\.json', reason = 'Node package lock, not sensitive'},
]
exclude-signatures = [
]
